/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LigasRouteImport } from './routes/ligas'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as CamposRouteImport } from './routes/campos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArbitragemRouteImport } from './routes/arbitragem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimeIdRouteImport } from './routes/time.$id'
import { Route as SumulaMatchIdRouteImport } from './routes/sumula.$matchId'
import { Route as PerfilEditarRouteImport } from './routes/perfil_.editar'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'
import { Route as JogadorIdRouteImport } from './routes/jogador.$id'
import { Route as ComplexoEditarRouteImport } from './routes/complexo_.editar'
import { Route as ComplexoIdRouteImport } from './routes/complexo.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CampoIdRouteImport } from './routes/campo.$id'
import { Route as ArbitroIdRouteImport } from './routes/arbitro.$id'
import { Route as ArbitragemEditarRouteImport } from './routes/arbitragem_.editar'
import { Route as TimeIdTransferirRouteImport } from './routes/time_.$id.transferir'
import { Route as CampoIdEditarRouteImport } from './routes/campo.$id.editar'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasRoute = LigasRouteImport.update({
  id: '/ligas',
  path: '/ligas',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const CamposRoute = CamposRouteImport.update({
  id: '/campos',
  path: '/campos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitragemRoute = ArbitragemRouteImport.update({
  id: '/arbitragem',
  path: '/arbitragem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeIdRoute = TimeIdRouteImport.update({
  id: '/time/$id',
  path: '/time/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SumulaMatchIdRoute = SumulaMatchIdRouteImport.update({
  id: '/sumula/$matchId',
  path: '/sumula/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilEditarRoute = PerfilEditarRouteImport.update({
  id: '/perfil_/editar',
  path: '/perfil/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PerfilRoute,
} as any)
const JogadorIdRoute = JogadorIdRouteImport.update({
  id: '/jogador/$id',
  path: '/jogador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexoEditarRoute = ComplexoEditarRouteImport.update({
  id: '/complexo_/editar',
  path: '/complexo/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexoIdRoute = ComplexoIdRouteImport.update({
  id: '/complexo/$id',
  path: '/complexo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoIdRoute = CampoIdRouteImport.update({
  id: '/campo/$id',
  path: '/campo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitroIdRoute = ArbitroIdRouteImport.update({
  id: '/arbitro/$id',
  path: '/arbitro/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitragemEditarRoute = ArbitragemEditarRouteImport.update({
  id: '/arbitragem_/editar',
  path: '/arbitragem/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeIdTransferirRoute = TimeIdTransferirRouteImport.update({
  id: '/time_/$id/transferir',
  path: '/time/$id/transferir',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoIdEditarRoute = CampoIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => CampoIdRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbitragem': typeof ArbitragemRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/campos': typeof CamposRoute
  '/desafios': typeof DesafiosRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ligas': typeof LigasRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/pro': typeof ProRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vagas': typeof VagasRoute
  '/arbitragem/editar': typeof ArbitragemEditarRoute
  '/arbitro/$id': typeof ArbitroIdRoute
  '/campo/$id': typeof CampoIdRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/complexo/$id': typeof ComplexoIdRoute
  '/complexo/editar': typeof ComplexoEditarRoute
  '/jogador/$id': typeof JogadorIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/sumula/$matchId': typeof SumulaMatchIdRoute
  '/time/$id': typeof TimeIdRoute
  '/campo/$id/editar': typeof CampoIdEditarRoute
  '/time/$id/transferir': typeof TimeIdTransferirRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbitragem': typeof ArbitragemRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/campos': typeof CamposRoute
  '/desafios': typeof DesafiosRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ligas': typeof LigasRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/pro': typeof ProRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vagas': typeof VagasRoute
  '/arbitragem/editar': typeof ArbitragemEditarRoute
  '/arbitro/$id': typeof ArbitroIdRoute
  '/campo/$id': typeof CampoIdRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/complexo/$id': typeof ComplexoIdRoute
  '/complexo/editar': typeof ComplexoEditarRoute
  '/jogador/$id': typeof JogadorIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/perfil/editar': typeof PerfilEditarRoute
  '/sumula/$matchId': typeof SumulaMatchIdRoute
  '/time/$id': typeof TimeIdRoute
  '/campo/$id/editar': typeof CampoIdEditarRoute
  '/time/$id/transferir': typeof TimeIdTransferirRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbitragem': typeof ArbitragemRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/campos': typeof CamposRoute
  '/desafios': typeof DesafiosRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ligas': typeof LigasRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/pro': typeof ProRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vagas': typeof VagasRoute
  '/arbitragem_/editar': typeof ArbitragemEditarRoute
  '/arbitro/$id': typeof ArbitroIdRoute
  '/campo/$id': typeof CampoIdRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/complexo/$id': typeof ComplexoIdRoute
  '/complexo_/editar': typeof ComplexoEditarRoute
  '/jogador/$id': typeof JogadorIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/perfil_/editar': typeof PerfilEditarRoute
  '/sumula/$matchId': typeof SumulaMatchIdRoute
  '/time/$id': typeof TimeIdRoute
  '/campo/$id/editar': typeof CampoIdEditarRoute
  '/time_/$id/transferir': typeof TimeIdTransferirRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbitragem'
    | '/auth'
    | '/buscar'
    | '/campos'
    | '/desafios'
    | '/forgot-password'
    | '/ligas'
    | '/onboarding'
    | '/painel'
    | '/perfil'
    | '/pro'
    | '/ranking'
    | '/reset-password'
    | '/vagas'
    | '/arbitragem/editar'
    | '/arbitro/$id'
    | '/campo/$id'
    | '/checkout/return'
    | '/complexo/$id'
    | '/complexo/editar'
    | '/jogador/$id'
    | '/perfil/$id'
    | '/perfil/editar'
    | '/sumula/$matchId'
    | '/time/$id'
    | '/campo/$id/editar'
    | '/time/$id/transferir'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbitragem'
    | '/auth'
    | '/buscar'
    | '/campos'
    | '/desafios'
    | '/forgot-password'
    | '/ligas'
    | '/onboarding'
    | '/painel'
    | '/perfil'
    | '/pro'
    | '/ranking'
    | '/reset-password'
    | '/vagas'
    | '/arbitragem/editar'
    | '/arbitro/$id'
    | '/campo/$id'
    | '/checkout/return'
    | '/complexo/$id'
    | '/complexo/editar'
    | '/jogador/$id'
    | '/perfil/$id'
    | '/perfil/editar'
    | '/sumula/$matchId'
    | '/time/$id'
    | '/campo/$id/editar'
    | '/time/$id/transferir'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/arbitragem'
    | '/auth'
    | '/buscar'
    | '/campos'
    | '/desafios'
    | '/forgot-password'
    | '/ligas'
    | '/onboarding'
    | '/painel'
    | '/perfil'
    | '/pro'
    | '/ranking'
    | '/reset-password'
    | '/vagas'
    | '/arbitragem_/editar'
    | '/arbitro/$id'
    | '/campo/$id'
    | '/checkout/return'
    | '/complexo/$id'
    | '/complexo_/editar'
    | '/jogador/$id'
    | '/perfil/$id'
    | '/perfil_/editar'
    | '/sumula/$matchId'
    | '/time/$id'
    | '/campo/$id/editar'
    | '/time_/$id/transferir'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbitragemRoute: typeof ArbitragemRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CamposRoute: typeof CamposRoute
  DesafiosRoute: typeof DesafiosRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LigasRoute: typeof LigasRoute
  OnboardingRoute: typeof OnboardingRoute
  PainelRoute: typeof PainelRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  ProRoute: typeof ProRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VagasRoute: typeof VagasRoute
  ArbitragemEditarRoute: typeof ArbitragemEditarRoute
  ArbitroIdRoute: typeof ArbitroIdRoute
  CampoIdRoute: typeof CampoIdRouteWithChildren
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ComplexoIdRoute: typeof ComplexoIdRoute
  ComplexoEditarRoute: typeof ComplexoEditarRoute
  JogadorIdRoute: typeof JogadorIdRoute
  PerfilEditarRoute: typeof PerfilEditarRoute
  SumulaMatchIdRoute: typeof SumulaMatchIdRoute
  TimeIdRoute: typeof TimeIdRoute
  TimeIdTransferirRoute: typeof TimeIdTransferirRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas': {
      id: '/ligas'
      path: '/ligas'
      fullPath: '/ligas'
      preLoaderRoute: typeof LigasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campos': {
      id: '/campos'
      path: '/campos'
      fullPath: '/campos'
      preLoaderRoute: typeof CamposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitragem': {
      id: '/arbitragem'
      path: '/arbitragem'
      fullPath: '/arbitragem'
      preLoaderRoute: typeof ArbitragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/$id': {
      id: '/time/$id'
      path: '/time/$id'
      fullPath: '/time/$id'
      preLoaderRoute: typeof TimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sumula/$matchId': {
      id: '/sumula/$matchId'
      path: '/sumula/$matchId'
      fullPath: '/sumula/$matchId'
      preLoaderRoute: typeof SumulaMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil_/editar': {
      id: '/perfil_/editar'
      path: '/perfil/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof PerfilEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/jogador/$id': {
      id: '/jogador/$id'
      path: '/jogador/$id'
      fullPath: '/jogador/$id'
      preLoaderRoute: typeof JogadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexo_/editar': {
      id: '/complexo_/editar'
      path: '/complexo/editar'
      fullPath: '/complexo/editar'
      preLoaderRoute: typeof ComplexoEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexo/$id': {
      id: '/complexo/$id'
      path: '/complexo/$id'
      fullPath: '/complexo/$id'
      preLoaderRoute: typeof ComplexoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo/$id': {
      id: '/campo/$id'
      path: '/campo/$id'
      fullPath: '/campo/$id'
      preLoaderRoute: typeof CampoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitro/$id': {
      id: '/arbitro/$id'
      path: '/arbitro/$id'
      fullPath: '/arbitro/$id'
      preLoaderRoute: typeof ArbitroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitragem_/editar': {
      id: '/arbitragem_/editar'
      path: '/arbitragem/editar'
      fullPath: '/arbitragem/editar'
      preLoaderRoute: typeof ArbitragemEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time_/$id/transferir': {
      id: '/time_/$id/transferir'
      path: '/time/$id/transferir'
      fullPath: '/time/$id/transferir'
      preLoaderRoute: typeof TimeIdTransferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo/$id/editar': {
      id: '/campo/$id/editar'
      path: '/editar'
      fullPath: '/campo/$id/editar'
      preLoaderRoute: typeof CampoIdEditarRouteImport
      parentRoute: typeof CampoIdRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PerfilRouteChildren {
  PerfilIdRoute: typeof PerfilIdRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilIdRoute: PerfilIdRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

interface CampoIdRouteChildren {
  CampoIdEditarRoute: typeof CampoIdEditarRoute
}

const CampoIdRouteChildren: CampoIdRouteChildren = {
  CampoIdEditarRoute: CampoIdEditarRoute,
}

const CampoIdRouteWithChildren =
  CampoIdRoute._addFileChildren(CampoIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbitragemRoute: ArbitragemRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CamposRoute: CamposRoute,
  DesafiosRoute: DesafiosRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LigasRoute: LigasRoute,
  OnboardingRoute: OnboardingRoute,
  PainelRoute: PainelRoute,
  PerfilRoute: PerfilRouteWithChildren,
  ProRoute: ProRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VagasRoute: VagasRoute,
  ArbitragemEditarRoute: ArbitragemEditarRoute,
  ArbitroIdRoute: ArbitroIdRoute,
  CampoIdRoute: CampoIdRouteWithChildren,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ComplexoIdRoute: ComplexoIdRoute,
  ComplexoEditarRoute: ComplexoEditarRoute,
  JogadorIdRoute: JogadorIdRoute,
  PerfilEditarRoute: PerfilEditarRoute,
  SumulaMatchIdRoute: SumulaMatchIdRoute,
  TimeIdRoute: TimeIdRoute,
  TimeIdTransferirRoute: TimeIdTransferirRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
