/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LigasRouteImport } from './routes/ligas'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as CamposRouteImport } from './routes/campos'
import { Route as IndexRouteImport } from './routes/index'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasRoute = LigasRouteImport.update({
  id: '/ligas',
  path: '/ligas',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const CamposRoute = CamposRouteImport.update({
  id: '/campos',
  path: '/campos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campos': typeof CamposRoute
  '/desafios': typeof DesafiosRoute
  '/ligas': typeof LigasRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campos': typeof CamposRoute
  '/desafios': typeof DesafiosRoute
  '/ligas': typeof LigasRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campos': typeof CamposRoute
  '/desafios': typeof DesafiosRoute
  '/ligas': typeof LigasRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campos' | '/desafios' | '/ligas' | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campos' | '/desafios' | '/ligas' | '/perfil'
  id: '__root__' | '/' | '/campos' | '/desafios' | '/ligas' | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CamposRoute: typeof CamposRoute
  DesafiosRoute: typeof DesafiosRoute
  LigasRoute: typeof LigasRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas': {
      id: '/ligas'
      path: '/ligas'
      fullPath: '/ligas'
      preLoaderRoute: typeof LigasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campos': {
      id: '/campos'
      path: '/campos'
      fullPath: '/campos'
      preLoaderRoute: typeof CamposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CamposRoute: CamposRoute,
  DesafiosRoute: DesafiosRoute,
  LigasRoute: LigasRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
